- name: Install necessary packages for nginx
  apt:
    name: ['curl', 'gnupg2', 'ca-certificates', 'lsb-release']

- name: Install nginx repository
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu xenial nginx

- name: Add apt key of nginx
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes

- name: Extract default vhost configuration
  stat: 
    path: /etc/nginx/conf.d/default.conf
  register: defaultvhost

- name: Disable default virtualhost configuration
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.original
  when: defaultvhost.stat.exists

- name: Extract default nginx configuration
  stat: 
    path: /etc/nginx/nginx.conf
  register: defaultnginxconf

- name: Disable default nginx configuration
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.original
  when: defaultnginxconf.stat.exists

- name: Create main global nginx configuration 
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Create main nginx configuration for serving web application
  template:
    src: appnginx.conf.j2
    dest: /etc/nginx/conf.d/appnginx.conf
  notify: restart Nginx 
